### ISSUE TITLE
Request for Renaming the repo

### ISSUE THREAD

**Issue by amarts** [gluster/glusterfs-posix2#2]
Instead of creating 1 repo for every xlator, I propose to keep all the xlators, all experimental, and soon to be deprecated xlators to move to this repo, under similar path.

So, lets change the repo name as 'glusterfs-xlators' (or something similar)

Description can be "all those experimental and orphan xlators of glusterfs project would be kept here for people's reference!"

Let me know if it makes sense!

@ShyamsundarR @kalebskeithley @nixpanic Let me know what you all think, then removal of translators from glusterfs repo becomes much smoother!

**Comment by kalebskeithley** [comment]
renaming: easy. figuring out how to move from master to a branch requires work :-)
It was easier to just create a new repo and import these files onto a branch.

see the glusterfs-xlators repo.  I will delete this repo in a few days.
